:sparkles: Add server and replica conection
MrEarle/T2-SSDD-G6 pull request #18
Opened 2021-11-03 19:27 UTC by BenjaLepe

2021-11-03 19:35 UTC, BenjaLepe commented on src/name_server/main.py
> +
Se agregó el endpoint al DNS para obtener el address de la replica

2021-11-03 19:35 UTC, BenjaLepe commented on src/name_server/main.py
> +        return ""
Handler que retorna el address de la replica

2021-11-03 19:37 UTC, BenjaLepe commented on src/server/Server.py
> +
Cuando llega una conexión al servidor de scoketio, si pertenece a un servidor replicado se la pasamos al ServerCoordinator

2021-11-03 19:38 UTC, BenjaLepe commented on src/server/ServerCoordinator.py
> +                    return
En esta parte se solicita al DNS el address del servidor replicado y si existe se intenta establecer una conexión

2021-11-03 19:39 UTC, BenjaLepe commented on src/utils/networking.py
> +
función de networking para obtener el address del servidor replicado

2021-11-03 19:59 UTC, MrEarle requested changes

2021-11-03 19:59 UTC, MrEarle commented on src/server/ServerCoordinator.py
>                  sleep(0.1)
Como ahora tenemos ese `if addr:` en el `try`, quizas es mejor cambiar esto a:

```py
except Exception:
    pass
sleep(0.1)
```

De esta manera, si `addr` es siempre `None` o `""` (porque aun no hay una replica), no se tiene un `while True` usando muchos recursos innecesariamente.

2021-11-03 20:02 UTC, BenjaLepe commented on src/server/ServerCoordinator.py
>                  sleep(0.1)
toda la razón

2021-11-03 20:04 UTC, MrEarle approved these changes

2021-11-04 14:37 UTC, tatanpoker09 approved these changes
Todo bien, lo que si no entendi a cuales handlers se refiere que hay que setear en el TODO ServerCoordinator:48

2021-11-04 16:35 UTC, BenjaLepe commented
> 
> 
> Todo bien, lo que si no entendi a cuales handlers se refiere que hay que setear en el TODO ServerCoordinator:48

Por ahora tenemos el `on_disconnect` no más, pero después pueden ser necesarios otros handlers para coordinarse con la réplica

2021-11-04 21:20 UTC, merged